version: '3'

services:
  my-python-code:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # depends_on:
    #   - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - type: bind
        source: ./share-folder
        target: /app/share-folder
        bind:
          propagation: shared
      - type: bind
        source: ./data
        target: /app/data
        bind:
          propagation: shared
    restart: always 
    deploy:
      resources:
        limits:
          cpus: "4"   # Increased from 2 to 4 CPUs
          memory: "4G"  # Increased from 2G to 4G
        reservations:
          cpus: "2"   # Increased from 1 to 2 CPUs
          memory: "2G"  # Increased from 1G to 2G

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - 11434:11434
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "6"   
  #         memory: "10G"  
  #       reservations:
  #         cpus: "4"   
  #         memory: "6G"  

# volumes:
#   ollama_data:
  